### ISSUE TITLE
Unity Editor failed to load dlls

### ISSUE THREAD

**Issue by hellozyemlya** [kumaS-nu/NuGet-importer-for-Unity#1]
I am trying to use System.Text.Json installed by importe, but when trying to run play mode in editor, it fails to load some of the dependencies.

Once I move all downloaded dlls to the same folder, everything works as expected.
Is there a way to teach unity editor to seek for dlls everywhere, or maybe we can change importer in the way it puts all dlls in same folder?

**Comment by kumaS-nu** [comment]
OK. I tried that problem and it occurred on my machine too. That only occurs in the editor and won't happen after the build. (Because after the build, the plugins are collected in one folder.) But that's a problem, and I'll fix it soon.

**Comment by hellozyemlya** [comment]
@kumaS-nu thanks for such quick reply. Looking forward for solution you will choose.

ps: thought about moving everything to single folder automatically, but maybe there is some magic inside runtime that will allow us to dynamically extend lookup paths?

**Comment by kumaS-nu** [comment]
Maybe this will help. I will try some test.
https://docs.microsoft.com/en-US/dotnet/framework/deployment/how-the-runtime-locates-assemblies
https://www.mono-project.com/docs/advanced/assemblies-and-the-gac/

**Comment by kumaS-nu** [comment]
I did some tests and figured out the following things.

* Unity Editor's ( or playing mode's ) entry point is /your/installed/editor/Unity.exe. (This result was obvious, but it confirmed that the program is not run by another exe in the editor or play mode.)
* Assemblies with matching strong-name can be referenced anywhere.
* Assemblies with mismatched strong-name (version mismatch, etc.) can be referenced if they are in the same directory.

I made the decision to use Unity's functions, since assemblies used in Unity projects should not be registered in GAC and the Codebase of Unity.exe cannot be changed. As a result, I'll take the first solution you suggested (install the managed plugin in one directory).

**Comment by kumaS-nu** [comment]
I found out why the error occurred and why it was resolved...
https://github.com/Unity-Technologies/UnityCsReference/blob/master/Editor/Mono/AssemblyValidation.cs
L.410
If .dll are in the same folder, the version mismatch will not cause an error...
