### ISSUE TITLE
[BUG] 2020.3.25f1 fail to compile The name 'NuGet' does not exist in the current context.

### ISSUE THREAD

**Issue by iamabigartist** [kumaS-nu/NuGet-importer-for-Unity#11]
After installing the package:
![image](https://user-images.githubusercontent.com/53459343/147398512-aeaa327f-a447-4695-a4a1-596b51cda9ec.png)

**Comment by iamabigartist** [comment]
The NuGet file was fully ignored due to the macro #IF ZIP_AVAILABLE.
So what control the zip available?

**Comment by kumaS-nu** [comment]
Thank you for your report.
This package uses the ZipFile class to unpack the NuGet package, which is not available in Unity by default. Therefore, I enclose the affected code with ZIP_AVAILABLE to avoid errors. Next, I make the ZipFile class available, and define ZIP_AVAILABLE to make this work.
This bug is completely my mistake. This bug is caused by not correctly enclosing the affected code with ZIP_AVAILABLE.
I will fix it right now.

**Comment by iamabigartist** [comment]
Thanks! Can't wait to use your importer~~

**Comment by kumaS-nu** [comment]
I fixed this as v2.0.1, and it will work. If this still doesn't work, please feel free to comment.

**Comment by iamabigartist** [comment]
Hi, it still does not work. I saw you wrap all the code with #if ZIP_AVAILABLE, so now the whole package - all the code have been **ignored** cause it seems the macro is not activated in my project.  I wonder where you #define the ZIP_AVAILABLE macro or how can I trigger it?

**Comment by iamabigartist** [comment]
OK, so it now works. The reason cause it was I 
accidentally change the 
-r:System.IO.Compression.FileSystem.dll in csc.rsp to 
-r: System.IO.Compression.FileSystem.dll,
which cause the compile arg ignored maybe.
