### ISSUE TITLE
Delay before sending "Search" request after typing text in "search field"

### ISSUE THREAD

**Issue by IvanMurzak** [kumaS-nu/NuGet-importer-for-Unity#32]
First of all, you made an amazing plugin! This is much better than NuGetForUnity!

I just want to request a single feature that may improve usage. In my case, I have a slow internet connection, and when I type text into the search field it takes 5 seconds after each letter to search packages and doesn't allow me to continue typing. 

**My proposition**
Add a delay after each typed letter, before sending a network request. If a new letter was typed in the delay period - cancel the previous delay and create a new one. That is all. 

Just in case how to do that ease. In **UniRx** library for Unity exists a cool reactive method "Throttle", it does the job.

```C#
onSearchFieldUpdated
  .Throttle(TimeSpan.FromSeconds(1))
  .Subscribe(x =>
  {
    // Make a request here
  });
```

**Comment by kumaS-nu** [comment]
Sorry for the very late reply...

I have implemented the search asynchronously, so I should be able to type continuously, but I may have made a mistake in the implementation...

I will add the following options for those with unstable networks.
- Option to reduce the amount of data. (limit the retrieval of images; reduce the number of searches as you suggested.)
- Option to set the number of communication retries
- Option to set a timeout period

I know UniRx has great features, but I don't plan to use this package because I want to avoid dependence on other packages.
