### ISSUE TITLE
[BUG] Broken in Linux Editor with recent updates (ZIP_AVAILABLE?)

### ISSUE THREAD

**Issue by NoTuxNoBux** [kumaS-nu/NuGet-importer-for-Unity#39]
**Describe the bug**
On the Linux Editor in 2021.3, I can install the package just fine, but no menu items are ever added for the package. After some digging, it turns out `ZIP_AVAILABLE` is `false`, resulting in most of the code being compiled out.

**To Reproduce**

1. Install the package.
2. Focus Unity.

**Expected behavior**
The package works as intended and shows its menu items in Unity.

**Desktop (please complete the following information):**
 - OS: Arch Linux x86-64
 - Unity Version: 2021.3.3
 - Package Version: 2.3.1

**Additional context**
I reported some other bugs previously, so this package worked at some point. I wanted to get back to it today, but can't get it to actually work any more. I am on the .NET Standard 2.1 profile, and looked at the source code briefly, and see that it tries to write a `csc.rsp` file if necessary, and it is written, but it has no effect - according to the Unity documentation, [`csc.rsp` is not meant for the .NET Standard profile](https://docs.unity3d.com/Manual/dotnetProfileAssemblies.html) either.

Normally the `ZIP_AVAILABLE` symbol should be added regardless, however, but still Unity refuses to load the menu items. Is this perhaps a problem with Unity 2021.3, or do I have to add this define somewhere myself?

FWIW, removing all these directives fixes the issue.

**Comment by kumaS-nu** [comment]
Thank you for your report.
I am releasing this package for free (and developing it alone in a little time), so please forgive any omissions or mistakes.

- Define Symbols
I would like to ask you, did you set the Build Target other than standalone? After reviewing, I may have set the Define Symbol for the wrong Build Target. Since this package is an editor extension, I thought I needed to define the Define Symbol only for the standalone, but I may have to set it for the current Build Target.

- Timeout
Not sure why this passed when I tested this...
It may take some time to fix it because I need to change the timeout settings based on the communication state.

I'll fix both of them soon.

**Comment by NoTuxNoBux** [comment]
Thanks for responding.

> I am releasing this package for free (and developing it alone in a little time), so please forgive any omissions or mistakes.

No problem, everyone has bugs. I did not intend to come across as rude or privileged; I only report bugs to help further open source projects and so other people are aware of them (since not everyone reports bugs), and I understand that most of these types of projects are done by people in their spare time and at no cost, so I don't wanted it to sound like I expect it to be fixed soon - take your time!
