### ISSUE TITLE
Install button is still gray after many attempt on deleting wrong profile

### ISSUE THREAD

**Issue by shirok1** [kumaS-nu/NuGet-importer-for-Unity#44]
`\Library`, `\Nuget`, `\Packages\*\` is deleted.

![](https://user-images.githubusercontent.com/12044683/186191162-1908c9ff-d8e0-4e76-9b40-68d9f8baab74.png)

**Comment by kumaS-nu** [comment]
The settings file for this package is also located at `\ProjectSettings\existingPackages.xml` ,  `\ProjectSettings\NuGetImporterSettings.json` , `\ProjectSettings\packageAsmNames.json` , and `\ProjectSettings\rootPackages.xml` .

This is likely due to this package recognizing that `NetMQ` is already installed (outside of monitoring this package).
This behavior is to avoid installing additional assemblies that are already in the project and causing errors (e.g., the situation where `Newtonsoft.Json` is already installed by Plastic SCM).

I also tried installing `NetMQ`. I don't know why, but `System.ServiceModel.Syndication` is not in a dependency, and an error occurred. We should additionally install `System.ServiceModel.Syndication`.

**Comment by shirok1** [comment]
Ok, I figure out how to clean it up right, but I wish there be a reset button right in this plugin.

**Comment by kumaS-nu** [comment]
Indeed!!!
I'll make that!
