### ISSUE TITLE
[Question] The menu item don't display

### ISSUE THREAD

**Issue by SettingDust** [kumaS-nu/NuGet-importer-for-Unity#58]
**Question**
IDK why is it happend. It works only 1 time. I want to using this package to manage nuget. So, I removed all nuget install by nugetforunity. Then, after recompile the menu item disappear. And I can't make it appear again. 
I tried install nugetforunity and this package. After restart, the menu item of nugetforunity appearing. But not this package.
I have no idea for how can I debug for this. So creating a question

**Comment by SettingDust** [comment]
After install all dependency and there isn't any error. The menu item shows

**Comment by kumaS-nu** [comment]
The reason why NuGet importer for Unity does not start is due to a compile error. The package via UPM is distributing source code, so if your project has a compile error, it will not be loaded.
You can use the .unitypackage in the Release distributed pre-compiled as a workaround.
Configuring NuGet importer for Unity to place packages under Assets becomes the same package placement as NugetforUnity. You can change the placement to UPM by changing the setting. However, the package management may be unstable due to a lack of information about the package.

**Comment by SettingDust** [comment]
Nuget for unity is installed from openupm. Why is it works

**Comment by SettingDust** [comment]
Fixed after remove the `ZIP_AVAILABLE` from asmdef

**Comment by kumaS-nu** [comment]
Ummm. We need to research what happens this more detail.

ZIP_AVAILABLE is a flag that states that csc.rsp is set and can decompress Zip files. If we remove ZIP_AVAILABLE from asmdef, users get a compile error when introducing this package.

**Comment by SettingDust** [comment]
> We need to research what happens this more detail.

ya
